baseURL = "https://www.georgewolf.net/"
languageCode = "en-us"
title = "george@ot-Web:$◻️"
theme = "ink-free"
paginate = 5
enableRobotsTXT = true
features = ["repository"]

copyright = "no one owns ideas"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "echo $RANDOM"
       


	# Optional 64x64 avatar image.
	avatar = "/gotw_small.png"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents
	toc = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	footers = [ 
		"Killer Roombas",
		"Escaping underwater cages", "Underwater basket weaving", 
                "Failing ⬆️", "Tornados"
                ]
	

	# Github base url
	#github = "https://github.io/vignettes"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/georgeontheweb_"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Vignettes/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
